server:
  port: 8181

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_dev_test
    username: library_user
    password: library_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # options: validate | update | create | create-drop | none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
